In [1]:
import numpy as np

print('Numpy version: ', np.__version__)
print(dir(np))

Numpy version:  2.3.4
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [19]:
test_list = [1,2,3,4,5,6]

numpy_test_list_array = np.array(test_list)

print(numpy_test_list)
print(type(numpy_test_list))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [15]:
int_to_float_list = [1,4,50,100]
int_to_float_array = np.array(int_to_float_list, dtype=float)
print(int_to_float_array) # tulostaa [  1.   4.  50. 100.], eli np.array lisää desimaalin joka osoittaa int -> float

c = np.array(int_to_float_list, dtype=bool)
print(numpy_bool_array)

[  1.   4.  50. 100.]
[ True  True  True  True]


In [18]:
list_2d = [[1,2,3],[4,5,6],[7,8,9]]
numpy_2d = np.array(list_2d)

print(numpy_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
np_to_list = numpy_test_list_array.tolist() #np array can be converted back to the list using .tolist()
print(np_to_list)

[1, 2, 3, 4, 5, 6]


In [23]:
tuple = (1,2,3,4,5,6)
print(type(tuple)) #checking type
print('This tuple contains: ', tuple)

array_from_tuple = np.array(tuple) #we can use the same .array() method as with lists to convert tuples to np.arrays
print(type(array_from_tuple))
print('This is numpy array and contains: ', array_from_tuple)

<class 'tuple'>
This tuple contains:  (1, 2, 3, 4, 5, 6)
<class 'numpy.ndarray'>
This is numpy array and contains:  [1 2 3 4 5 6]


In [24]:
int_list = [-2, -5, -4, 0, 3, 3, 4, 1, 0, 50, -2]
int_array = np.array(int_list)
print(f'list: {int_list}, and array: {int_array}')
print(int_array.dtype)

list: [-2, -5, -4, 0, 3, 3, 4, 1, 0, 50, -2], and array: [-2 -5 -4  0  3  3  4  1  0 50 -2]
int64


In [27]:
array1 = np.array([[1,2,3,4]]) #2d array vain yhdellä arvolla(lista) 1 row, 4 column
array2 = np.array([[1],[2],[3],[4]]) # 2d array jossa 4 row, 1 column

print(array1.shape)
print(array2.shape)

(1, 4)
(4, 1)


In [28]:
#kokeillaan voidaanko tehdä broadcast, eli tehdä aritmeettisia operaatioita taulukoiden välillä
print(array1 * array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [29]:
#jos muutetaan array1 arvoja siten että sen shape on  (2,4) eli 2 row, 4 column, tämä ei enää toimi!
array1 = np.array([[1,2,3,4],[5,6,7,8]])
print(array1.shape) # (2, 4) ei toimi, taulukoiden row/column arvot täytyy joko olla samat tai
print(array2.shape) # (4, 1) arvon täytyy olla 1 toisessa sarakkeista

(2, 4)
(4, 1)


In [31]:
print(array1 * array2) # saadaan virhe ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [35]:
#we can also reshape our arrays using reshape(argument1, argument2)
array_2d = np.array([[1,2,3],[4,5,6]]) #array shaped(2,3)
reshaped = array_2d.reshape(3,2) # lets reshape it to form (3,2)
print(array_2d)
print(reshaped)

#array can also be flattened by using flatten()
flattened = array_2d.flatten() #shape (1,6)
print(flattened)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [39]:
#we can make rantom int and floats with using np.random.random()
random_float = np.random.random()
print(random_float)

random_floats = np.random.random(5) #makes an array of 5 random floats
print(random_floats)

0.8693139546759461
[0.52957056 0.46592342 0.23663369 0.77167899 0.47010725]


In [57]:
random_int = np.random.randint(0,11) # for integer values we need to give a range from where to where we want a random value

print(random_int)

9


In [61]:
#we can also generate random arrays
random_array = np.random.randint(1,11, size = 4)
print(random_array)

#and also in different shapes!
random_array_3d = np.random.randint(1,11, size=(3,3))
print(random_array_3d)

[ 2  5 10 10]
[[4 8 3]
 [8 3 5]
 [4 3 2]]


In [62]:
normal_array = np.random.normal(100, 1, 10)
print(normal_array)

[ 98.22013218 100.41314948  99.25758884  99.52231627 100.36017685
  99.28806027 101.10209358 100.35081959 100.40700415 101.50056895]
