In [1]:
import numpy as np

print('Numpy version: ', np.__version__)
print(dir(np))

Numpy version:  2.3.4
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [19]:
test_list = [1,2,3,4,5,6]

numpy_test_list_array = np.array(test_list)

print(numpy_test_list)
print(type(numpy_test_list))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [15]:
int_to_float_list = [1,4,50,100]
int_to_float_array = np.array(int_to_float_list, dtype=float)
print(int_to_float_array) # tulostaa [  1.   4.  50. 100.], eli np.array lisää desimaalin joka osoittaa int -> float

c = np.array(int_to_float_list, dtype=bool)
print(numpy_bool_array)

[  1.   4.  50. 100.]
[ True  True  True  True]


In [18]:
list_2d = [[1,2,3],[4,5,6],[7,8,9]]
numpy_2d = np.array(list_2d)

print(numpy_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
np_to_list = numpy_test_list_array.tolist() #np array can be converted back to the list using .tolist()
print(np_to_list)

[1, 2, 3, 4, 5, 6]


In [23]:
tuple = (1,2,3,4,5,6)
print(type(tuple)) #checking type
print('This tuple contains: ', tuple)

array_from_tuple = np.array(tuple) #we can use the same .array() method as with lists to convert tuples to np.arrays
print(type(array_from_tuple))
print('This is numpy array and contains: ', array_from_tuple)

<class 'tuple'>
This tuple contains:  (1, 2, 3, 4, 5, 6)
<class 'numpy.ndarray'>
This is numpy array and contains:  [1 2 3 4 5 6]
